/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "ap-southeast-2",
    "aws_cognito_identity_pool_id": "ap-southeast-2:7d92e33e-c691-49c5-a7c8-7e3a0303ffe6",
    "aws_cognito_region": "ap-southeast-2",
    "aws_user_pools_id": "ap-southeast-2_KzPUOnVKo",
    "aws_user_pools_web_client_id": "61rht0ncrjt546cc1hi3jp10sb",
    "oauth": {
        domain: "receiptpal-auth-2.auth.ap-southeast-2.amazoncognito.com",
        scope: ["openid","email","profile"],
        redirectSignIn:  "https://main.d3iynbxrksi5iq.amplifyapp.com/upload",
        redirectSignOut: "https://main.d3iynbxrksi5iq.amplifyapp.com/",
        responseType: "code"
    },
    "aws_cognito_username_attributes": [
        "EMAIL"
    ],
    "aws_cognito_social_providers": ["GOOGLE"],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ],
    "authenticationFlowType": "USER_PASSWORD_AUTH"
};


export default awsmobile;
